/* Generated by glcoregen v2 */
#include <glcore_330.h>

#ifdef USING_SDL

#include <SDL2/SDL.h>

static void open_libgl(void)
{
	SDL_GL_LoadLibrary(NULL);
}

static void close_libgl(void)
{
	SDL_GL_UnloadLibrary();
}

typedef void (*VOIDFUNC)(void);

static VOIDFUNC get_proc(const char *proc)
{
    // no valid cast between pointer to function and pointer to object
    union {
        void *p;
        VOIDFUNC f;
    } ptr;

    ptr.p = SDL_GL_GetProcAddress(proc);

    return ptr.f;
}

#else

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN 1
#include <windows.h>

static HMODULE libgl;

static void open_libgl(void)
{
	libgl = LoadLibraryA("opengl32.dll");
}

static void close_libgl(void)
{
	FreeLibrary(libgl);
}

static void *get_proc(const char *proc)
{
	void *res;

	res = wglGetProcAddress(proc);
	if (!res)
		res = GetProcAddress(libgl, proc);
	return res;
}
#elif defined(__APPLE__) || defined(__APPLE_CC__)
#include <Carbon/Carbon.h>

CFBundleRef bundle;
CFURLRef bundleURL;

static void open_libgl(void)
{
	bundleURL = CFURLCreateWithFileSystemPath(kCFAllocatorDefault,
		CFSTR("/System/Library/Frameworks/OpenGL.framework"),
		kCFURLPOSIXPathStyle, true);

	bundle = CFBundleCreate(kCFAllocatorDefault, bundleURL);
	assert(bundle != NULL);
}

static void close_libgl(void)
{
	CFRelease(bundle);
	CFRelease(bundleURL);
}

static void *get_proc(const char *proc)
{
	void *res;

	CFStringRef procname = CFStringCreateWithCString(kCFAllocatorDefault, proc,
		kCFStringEncodingASCII);
	res = CFBundleGetFunctionPointerForName(bundle, procname);
	CFRelease(procname);
	return res;
}
#else
#include <dlfcn.h>
#include <GL/glx.h>

static void *libgl;

static void open_libgl(void)
{
	libgl = dlopen("libGL.so.1", RTLD_LAZY | RTLD_GLOBAL);
}

static void close_libgl(void)
{
	dlclose(libgl);
}

static void *get_proc(const char *proc)
{
	void *res;

	res = glXGetProcAddress((const GLubyte *) proc);
	if (!res)
		res = dlsym(libgl, proc);
	return res;
}
#endif

#endif /* USING_SDL */

static void load_procs(void);
static void load_exts(void);

int glLoadFunctions(void)
{
	open_libgl();
	load_procs();
	close_libgl();
	return 1;
}

int glLoadExtensions(void)
{
	open_libgl();
	load_exts();
	close_libgl();
	return 1;
}

void *nativeGetProcAddress(const char *proc)
{
	return get_proc(proc);
}

PFNGLCULLFACEPROC _glCullFace;
PFNGLFRONTFACEPROC _glFrontFace;
PFNGLHINTPROC _glHint;
PFNGLLINEWIDTHPROC _glLineWidth;
PFNGLPOINTSIZEPROC _glPointSize;
PFNGLPOLYGONMODEPROC _glPolygonMode;
PFNGLSCISSORPROC _glScissor;
PFNGLTEXPARAMETERFPROC _glTexParameterf;
PFNGLTEXPARAMETERFVPROC _glTexParameterfv;
PFNGLTEXPARAMETERIPROC _glTexParameteri;
PFNGLTEXPARAMETERIVPROC _glTexParameteriv;
PFNGLTEXIMAGE1DPROC _glTexImage1D;
PFNGLTEXIMAGE2DPROC _glTexImage2D;
PFNGLDRAWBUFFERPROC _glDrawBuffer;
PFNGLCLEARPROC _glClear;
PFNGLCLEARCOLORPROC _glClearColor;
PFNGLCLEARSTENCILPROC _glClearStencil;
PFNGLCLEARDEPTHPROC _glClearDepth;
PFNGLSTENCILMASKPROC _glStencilMask;
PFNGLCOLORMASKPROC _glColorMask;
PFNGLDEPTHMASKPROC _glDepthMask;
PFNGLDISABLEPROC _glDisable;
PFNGLENABLEPROC _glEnable;
PFNGLFINISHPROC _glFinish;
PFNGLFLUSHPROC _glFlush;
PFNGLBLENDFUNCPROC _glBlendFunc;
PFNGLLOGICOPPROC _glLogicOp;
PFNGLSTENCILFUNCPROC _glStencilFunc;
PFNGLSTENCILOPPROC _glStencilOp;
PFNGLDEPTHFUNCPROC _glDepthFunc;
PFNGLPIXELSTOREFPROC _glPixelStoref;
PFNGLPIXELSTOREIPROC _glPixelStorei;
PFNGLREADBUFFERPROC _glReadBuffer;
PFNGLREADPIXELSPROC _glReadPixels;
PFNGLGETBOOLEANVPROC _glGetBooleanv;
PFNGLGETDOUBLEVPROC _glGetDoublev;
PFNGLGETERRORPROC _glGetError;
PFNGLGETFLOATVPROC _glGetFloatv;
PFNGLGETINTEGERVPROC _glGetIntegerv;
PFNGLGETSTRINGPROC _glGetString;
PFNGLGETTEXIMAGEPROC _glGetTexImage;
PFNGLGETTEXPARAMETERFVPROC _glGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC _glGetTexParameteriv;
PFNGLGETTEXLEVELPARAMETERFVPROC _glGetTexLevelParameterfv;
PFNGLGETTEXLEVELPARAMETERIVPROC _glGetTexLevelParameteriv;
PFNGLISENABLEDPROC _glIsEnabled;
PFNGLDEPTHRANGEPROC _glDepthRange;
PFNGLVIEWPORTPROC _glViewport;
PFNGLDRAWARRAYSPROC _glDrawArrays;
PFNGLDRAWELEMENTSPROC _glDrawElements;
PFNGLPOLYGONOFFSETPROC _glPolygonOffset;
PFNGLCOPYTEXIMAGE1DPROC _glCopyTexImage1D;
PFNGLCOPYTEXIMAGE2DPROC _glCopyTexImage2D;
PFNGLCOPYTEXSUBIMAGE1DPROC _glCopyTexSubImage1D;
PFNGLCOPYTEXSUBIMAGE2DPROC _glCopyTexSubImage2D;
PFNGLTEXSUBIMAGE1DPROC _glTexSubImage1D;
PFNGLTEXSUBIMAGE2DPROC _glTexSubImage2D;
PFNGLBINDTEXTUREPROC _glBindTexture;
PFNGLDELETETEXTURESPROC _glDeleteTextures;
PFNGLGENTEXTURESPROC _glGenTextures;
PFNGLISTEXTUREPROC _glIsTexture;
PFNGLDRAWRANGEELEMENTSPROC _glDrawRangeElements;
PFNGLTEXIMAGE3DPROC _glTexImage3D;
PFNGLTEXSUBIMAGE3DPROC _glTexSubImage3D;
PFNGLCOPYTEXSUBIMAGE3DPROC _glCopyTexSubImage3D;
PFNGLACTIVETEXTUREPROC _glActiveTexture;
PFNGLSAMPLECOVERAGEPROC _glSampleCoverage;
PFNGLCOMPRESSEDTEXIMAGE3DPROC _glCompressedTexImage3D;
PFNGLCOMPRESSEDTEXIMAGE2DPROC _glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXIMAGE1DPROC _glCompressedTexImage1D;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC _glCompressedTexSubImage3D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC _glCompressedTexSubImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC _glCompressedTexSubImage1D;
PFNGLGETCOMPRESSEDTEXIMAGEPROC _glGetCompressedTexImage;
PFNGLBLENDFUNCSEPARATEPROC _glBlendFuncSeparate;
PFNGLMULTIDRAWARRAYSPROC _glMultiDrawArrays;
PFNGLMULTIDRAWELEMENTSPROC _glMultiDrawElements;
PFNGLPOINTPARAMETERFPROC _glPointParameterf;
PFNGLPOINTPARAMETERFVPROC _glPointParameterfv;
PFNGLPOINTPARAMETERIPROC _glPointParameteri;
PFNGLPOINTPARAMETERIVPROC _glPointParameteriv;
PFNGLBLENDCOLORPROC _glBlendColor;
PFNGLBLENDEQUATIONPROC _glBlendEquation;
PFNGLGENQUERIESPROC _glGenQueries;
PFNGLDELETEQUERIESPROC _glDeleteQueries;
PFNGLISQUERYPROC _glIsQuery;
PFNGLBEGINQUERYPROC _glBeginQuery;
PFNGLENDQUERYPROC _glEndQuery;
PFNGLGETQUERYIVPROC _glGetQueryiv;
PFNGLGETQUERYOBJECTIVPROC _glGetQueryObjectiv;
PFNGLGETQUERYOBJECTUIVPROC _glGetQueryObjectuiv;
PFNGLBINDBUFFERPROC _glBindBuffer;
PFNGLDELETEBUFFERSPROC _glDeleteBuffers;
PFNGLGENBUFFERSPROC _glGenBuffers;
PFNGLISBUFFERPROC _glIsBuffer;
PFNGLBUFFERDATAPROC _glBufferData;
PFNGLBUFFERSUBDATAPROC _glBufferSubData;
PFNGLGETBUFFERSUBDATAPROC _glGetBufferSubData;
PFNGLMAPBUFFERPROC _glMapBuffer;
PFNGLUNMAPBUFFERPROC _glUnmapBuffer;
PFNGLGETBUFFERPARAMETERIVPROC _glGetBufferParameteriv;
PFNGLGETBUFFERPOINTERVPROC _glGetBufferPointerv;
PFNGLBLENDEQUATIONSEPARATEPROC _glBlendEquationSeparate;
PFNGLDRAWBUFFERSPROC _glDrawBuffers;
PFNGLSTENCILOPSEPARATEPROC _glStencilOpSeparate;
PFNGLSTENCILFUNCSEPARATEPROC _glStencilFuncSeparate;
PFNGLSTENCILMASKSEPARATEPROC _glStencilMaskSeparate;
PFNGLATTACHSHADERPROC _glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC _glBindAttribLocation;
PFNGLCOMPILESHADERPROC _glCompileShader;
PFNGLCREATEPROGRAMPROC _glCreateProgram;
PFNGLCREATESHADERPROC _glCreateShader;
PFNGLDELETEPROGRAMPROC _glDeleteProgram;
PFNGLDELETESHADERPROC _glDeleteShader;
PFNGLDETACHSHADERPROC _glDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC _glDisableVertexAttribArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC _glEnableVertexAttribArray;
PFNGLGETACTIVEATTRIBPROC _glGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC _glGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC _glGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC _glGetAttribLocation;
PFNGLGETPROGRAMIVPROC _glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC _glGetProgramInfoLog;
PFNGLGETSHADERIVPROC _glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC _glGetShaderInfoLog;
PFNGLGETSHADERSOURCEPROC _glGetShaderSource;
PFNGLGETUNIFORMLOCATIONPROC _glGetUniformLocation;
PFNGLGETUNIFORMFVPROC _glGetUniformfv;
PFNGLGETUNIFORMIVPROC _glGetUniformiv;
PFNGLGETVERTEXATTRIBDVPROC _glGetVertexAttribdv;
PFNGLGETVERTEXATTRIBFVPROC _glGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC _glGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC _glGetVertexAttribPointerv;
PFNGLISPROGRAMPROC _glIsProgram;
PFNGLISSHADERPROC _glIsShader;
PFNGLLINKPROGRAMPROC _glLinkProgram;
PFNGLSHADERSOURCEPROC _glShaderSource;
PFNGLUSEPROGRAMPROC _glUseProgram;
PFNGLUNIFORM1FPROC _glUniform1f;
PFNGLUNIFORM2FPROC _glUniform2f;
PFNGLUNIFORM3FPROC _glUniform3f;
PFNGLUNIFORM4FPROC _glUniform4f;
PFNGLUNIFORM1IPROC _glUniform1i;
PFNGLUNIFORM2IPROC _glUniform2i;
PFNGLUNIFORM3IPROC _glUniform3i;
PFNGLUNIFORM4IPROC _glUniform4i;
PFNGLUNIFORM1FVPROC _glUniform1fv;
PFNGLUNIFORM2FVPROC _glUniform2fv;
PFNGLUNIFORM3FVPROC _glUniform3fv;
PFNGLUNIFORM4FVPROC _glUniform4fv;
PFNGLUNIFORM1IVPROC _glUniform1iv;
PFNGLUNIFORM2IVPROC _glUniform2iv;
PFNGLUNIFORM3IVPROC _glUniform3iv;
PFNGLUNIFORM4IVPROC _glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC _glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC _glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC _glUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC _glValidateProgram;
PFNGLVERTEXATTRIB1DPROC _glVertexAttrib1d;
PFNGLVERTEXATTRIB1DVPROC _glVertexAttrib1dv;
PFNGLVERTEXATTRIB1FPROC _glVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC _glVertexAttrib1fv;
PFNGLVERTEXATTRIB1SPROC _glVertexAttrib1s;
PFNGLVERTEXATTRIB1SVPROC _glVertexAttrib1sv;
PFNGLVERTEXATTRIB2DPROC _glVertexAttrib2d;
PFNGLVERTEXATTRIB2DVPROC _glVertexAttrib2dv;
PFNGLVERTEXATTRIB2FPROC _glVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC _glVertexAttrib2fv;
PFNGLVERTEXATTRIB2SPROC _glVertexAttrib2s;
PFNGLVERTEXATTRIB2SVPROC _glVertexAttrib2sv;
PFNGLVERTEXATTRIB3DPROC _glVertexAttrib3d;
PFNGLVERTEXATTRIB3DVPROC _glVertexAttrib3dv;
PFNGLVERTEXATTRIB3FPROC _glVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC _glVertexAttrib3fv;
PFNGLVERTEXATTRIB3SPROC _glVertexAttrib3s;
PFNGLVERTEXATTRIB3SVPROC _glVertexAttrib3sv;
PFNGLVERTEXATTRIB4NBVPROC _glVertexAttrib4Nbv;
PFNGLVERTEXATTRIB4NIVPROC _glVertexAttrib4Niv;
PFNGLVERTEXATTRIB4NSVPROC _glVertexAttrib4Nsv;
PFNGLVERTEXATTRIB4NUBPROC _glVertexAttrib4Nub;
PFNGLVERTEXATTRIB4NUBVPROC _glVertexAttrib4Nubv;
PFNGLVERTEXATTRIB4NUIVPROC _glVertexAttrib4Nuiv;
PFNGLVERTEXATTRIB4NUSVPROC _glVertexAttrib4Nusv;
PFNGLVERTEXATTRIB4BVPROC _glVertexAttrib4bv;
PFNGLVERTEXATTRIB4DPROC _glVertexAttrib4d;
PFNGLVERTEXATTRIB4DVPROC _glVertexAttrib4dv;
PFNGLVERTEXATTRIB4FPROC _glVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC _glVertexAttrib4fv;
PFNGLVERTEXATTRIB4IVPROC _glVertexAttrib4iv;
PFNGLVERTEXATTRIB4SPROC _glVertexAttrib4s;
PFNGLVERTEXATTRIB4SVPROC _glVertexAttrib4sv;
PFNGLVERTEXATTRIB4UBVPROC _glVertexAttrib4ubv;
PFNGLVERTEXATTRIB4UIVPROC _glVertexAttrib4uiv;
PFNGLVERTEXATTRIB4USVPROC _glVertexAttrib4usv;
PFNGLVERTEXATTRIBPOINTERPROC _glVertexAttribPointer;
PFNGLUNIFORMMATRIX2X3FVPROC _glUniformMatrix2x3fv;
PFNGLUNIFORMMATRIX3X2FVPROC _glUniformMatrix3x2fv;
PFNGLUNIFORMMATRIX2X4FVPROC _glUniformMatrix2x4fv;
PFNGLUNIFORMMATRIX4X2FVPROC _glUniformMatrix4x2fv;
PFNGLUNIFORMMATRIX3X4FVPROC _glUniformMatrix3x4fv;
PFNGLUNIFORMMATRIX4X3FVPROC _glUniformMatrix4x3fv;
PFNGLCOLORMASKIPROC _glColorMaski;
PFNGLGETBOOLEANI_VPROC _glGetBooleani_v;
PFNGLGETINTEGERI_VPROC _glGetIntegeri_v;
PFNGLENABLEIPROC _glEnablei;
PFNGLDISABLEIPROC _glDisablei;
PFNGLISENABLEDIPROC _glIsEnabledi;
PFNGLBEGINTRANSFORMFEEDBACKPROC _glBeginTransformFeedback;
PFNGLENDTRANSFORMFEEDBACKPROC _glEndTransformFeedback;
PFNGLBINDBUFFERRANGEPROC _glBindBufferRange;
PFNGLBINDBUFFERBASEPROC _glBindBufferBase;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC _glTransformFeedbackVaryings;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC _glGetTransformFeedbackVarying;
PFNGLCLAMPCOLORPROC _glClampColor;
PFNGLBEGINCONDITIONALRENDERPROC _glBeginConditionalRender;
PFNGLENDCONDITIONALRENDERPROC _glEndConditionalRender;
PFNGLVERTEXATTRIBIPOINTERPROC _glVertexAttribIPointer;
PFNGLGETVERTEXATTRIBIIVPROC _glGetVertexAttribIiv;
PFNGLGETVERTEXATTRIBIUIVPROC _glGetVertexAttribIuiv;
PFNGLVERTEXATTRIBI1IPROC _glVertexAttribI1i;
PFNGLVERTEXATTRIBI2IPROC _glVertexAttribI2i;
PFNGLVERTEXATTRIBI3IPROC _glVertexAttribI3i;
PFNGLVERTEXATTRIBI4IPROC _glVertexAttribI4i;
PFNGLVERTEXATTRIBI1UIPROC _glVertexAttribI1ui;
PFNGLVERTEXATTRIBI2UIPROC _glVertexAttribI2ui;
PFNGLVERTEXATTRIBI3UIPROC _glVertexAttribI3ui;
PFNGLVERTEXATTRIBI4UIPROC _glVertexAttribI4ui;
PFNGLVERTEXATTRIBI1IVPROC _glVertexAttribI1iv;
PFNGLVERTEXATTRIBI2IVPROC _glVertexAttribI2iv;
PFNGLVERTEXATTRIBI3IVPROC _glVertexAttribI3iv;
PFNGLVERTEXATTRIBI4IVPROC _glVertexAttribI4iv;
PFNGLVERTEXATTRIBI1UIVPROC _glVertexAttribI1uiv;
PFNGLVERTEXATTRIBI2UIVPROC _glVertexAttribI2uiv;
PFNGLVERTEXATTRIBI3UIVPROC _glVertexAttribI3uiv;
PFNGLVERTEXATTRIBI4UIVPROC _glVertexAttribI4uiv;
PFNGLVERTEXATTRIBI4BVPROC _glVertexAttribI4bv;
PFNGLVERTEXATTRIBI4SVPROC _glVertexAttribI4sv;
PFNGLVERTEXATTRIBI4UBVPROC _glVertexAttribI4ubv;
PFNGLVERTEXATTRIBI4USVPROC _glVertexAttribI4usv;
PFNGLGETUNIFORMUIVPROC _glGetUniformuiv;
PFNGLBINDFRAGDATALOCATIONPROC _glBindFragDataLocation;
PFNGLGETFRAGDATALOCATIONPROC _glGetFragDataLocation;
PFNGLUNIFORM1UIPROC _glUniform1ui;
PFNGLUNIFORM2UIPROC _glUniform2ui;
PFNGLUNIFORM3UIPROC _glUniform3ui;
PFNGLUNIFORM4UIPROC _glUniform4ui;
PFNGLUNIFORM1UIVPROC _glUniform1uiv;
PFNGLUNIFORM2UIVPROC _glUniform2uiv;
PFNGLUNIFORM3UIVPROC _glUniform3uiv;
PFNGLUNIFORM4UIVPROC _glUniform4uiv;
PFNGLTEXPARAMETERIIVPROC _glTexParameterIiv;
PFNGLTEXPARAMETERIUIVPROC _glTexParameterIuiv;
PFNGLGETTEXPARAMETERIIVPROC _glGetTexParameterIiv;
PFNGLGETTEXPARAMETERIUIVPROC _glGetTexParameterIuiv;
PFNGLCLEARBUFFERIVPROC _glClearBufferiv;
PFNGLCLEARBUFFERUIVPROC _glClearBufferuiv;
PFNGLCLEARBUFFERFVPROC _glClearBufferfv;
PFNGLCLEARBUFFERFIPROC _glClearBufferfi;
PFNGLGETSTRINGIPROC _glGetStringi;
PFNGLISRENDERBUFFERPROC _glIsRenderbuffer;
PFNGLBINDRENDERBUFFERPROC _glBindRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC _glDeleteRenderbuffers;
PFNGLGENRENDERBUFFERSPROC _glGenRenderbuffers;
PFNGLRENDERBUFFERSTORAGEPROC _glRenderbufferStorage;
PFNGLGETRENDERBUFFERPARAMETERIVPROC _glGetRenderbufferParameteriv;
PFNGLISFRAMEBUFFERPROC _glIsFramebuffer;
PFNGLBINDFRAMEBUFFERPROC _glBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC _glDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC _glGenFramebuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC _glCheckFramebufferStatus;
PFNGLFRAMEBUFFERTEXTURE1DPROC _glFramebufferTexture1D;
PFNGLFRAMEBUFFERTEXTURE2DPROC _glFramebufferTexture2D;
PFNGLFRAMEBUFFERTEXTURE3DPROC _glFramebufferTexture3D;
PFNGLFRAMEBUFFERRENDERBUFFERPROC _glFramebufferRenderbuffer;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC _glGetFramebufferAttachmentParameteriv;
PFNGLGENERATEMIPMAPPROC _glGenerateMipmap;
PFNGLBLITFRAMEBUFFERPROC _glBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC _glRenderbufferStorageMultisample;
PFNGLFRAMEBUFFERTEXTURELAYERPROC _glFramebufferTextureLayer;
PFNGLMAPBUFFERRANGEPROC _glMapBufferRange;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC _glFlushMappedBufferRange;
PFNGLBINDVERTEXARRAYPROC _glBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC _glDeleteVertexArrays;
PFNGLGENVERTEXARRAYSPROC _glGenVertexArrays;
PFNGLISVERTEXARRAYPROC _glIsVertexArray;
PFNGLDRAWARRAYSINSTANCEDPROC _glDrawArraysInstanced;
PFNGLDRAWELEMENTSINSTANCEDPROC _glDrawElementsInstanced;
PFNGLTEXBUFFERPROC _glTexBuffer;
PFNGLPRIMITIVERESTARTINDEXPROC _glPrimitiveRestartIndex;
PFNGLCOPYBUFFERSUBDATAPROC _glCopyBufferSubData;
PFNGLGETUNIFORMINDICESPROC _glGetUniformIndices;
PFNGLGETACTIVEUNIFORMSIVPROC _glGetActiveUniformsiv;
PFNGLGETACTIVEUNIFORMNAMEPROC _glGetActiveUniformName;
PFNGLGETUNIFORMBLOCKINDEXPROC _glGetUniformBlockIndex;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC _glGetActiveUniformBlockiv;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC _glGetActiveUniformBlockName;
PFNGLUNIFORMBLOCKBINDINGPROC _glUniformBlockBinding;
PFNGLDRAWELEMENTSBASEVERTEXPROC _glDrawElementsBaseVertex;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC _glDrawRangeElementsBaseVertex;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC _glDrawElementsInstancedBaseVertex;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC _glMultiDrawElementsBaseVertex;
PFNGLPROVOKINGVERTEXPROC _glProvokingVertex;
PFNGLFENCESYNCPROC _glFenceSync;
PFNGLISSYNCPROC _glIsSync;
PFNGLDELETESYNCPROC _glDeleteSync;
PFNGLCLIENTWAITSYNCPROC _glClientWaitSync;
PFNGLWAITSYNCPROC _glWaitSync;
PFNGLGETINTEGER64VPROC _glGetInteger64v;
PFNGLGETSYNCIVPROC _glGetSynciv;
PFNGLGETINTEGER64I_VPROC _glGetInteger64i_v;
PFNGLGETBUFFERPARAMETERI64VPROC _glGetBufferParameteri64v;
PFNGLFRAMEBUFFERTEXTUREPROC _glFramebufferTexture;
PFNGLTEXIMAGE2DMULTISAMPLEPROC _glTexImage2DMultisample;
PFNGLTEXIMAGE3DMULTISAMPLEPROC _glTexImage3DMultisample;
PFNGLGETMULTISAMPLEFVPROC _glGetMultisamplefv;
PFNGLSAMPLEMASKIPROC _glSampleMaski;
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC _glBindFragDataLocationIndexed;
PFNGLGETFRAGDATAINDEXPROC _glGetFragDataIndex;
PFNGLGENSAMPLERSPROC _glGenSamplers;
PFNGLDELETESAMPLERSPROC _glDeleteSamplers;
PFNGLISSAMPLERPROC _glIsSampler;
PFNGLBINDSAMPLERPROC _glBindSampler;
PFNGLSAMPLERPARAMETERIPROC _glSamplerParameteri;
PFNGLSAMPLERPARAMETERIVPROC _glSamplerParameteriv;
PFNGLSAMPLERPARAMETERFPROC _glSamplerParameterf;
PFNGLSAMPLERPARAMETERFVPROC _glSamplerParameterfv;
PFNGLSAMPLERPARAMETERIIVPROC _glSamplerParameterIiv;
PFNGLSAMPLERPARAMETERIUIVPROC _glSamplerParameterIuiv;
PFNGLGETSAMPLERPARAMETERIVPROC _glGetSamplerParameteriv;
PFNGLGETSAMPLERPARAMETERIIVPROC _glGetSamplerParameterIiv;
PFNGLGETSAMPLERPARAMETERFVPROC _glGetSamplerParameterfv;
PFNGLGETSAMPLERPARAMETERIUIVPROC _glGetSamplerParameterIuiv;
PFNGLQUERYCOUNTERPROC _glQueryCounter;
PFNGLGETQUERYOBJECTI64VPROC _glGetQueryObjecti64v;
PFNGLGETQUERYOBJECTUI64VPROC _glGetQueryObjectui64v;
PFNGLVERTEXATTRIBDIVISORPROC _glVertexAttribDivisor;
PFNGLVERTEXATTRIBP1UIPROC _glVertexAttribP1ui;
PFNGLVERTEXATTRIBP1UIVPROC _glVertexAttribP1uiv;
PFNGLVERTEXATTRIBP2UIPROC _glVertexAttribP2ui;
PFNGLVERTEXATTRIBP2UIVPROC _glVertexAttribP2uiv;
PFNGLVERTEXATTRIBP3UIPROC _glVertexAttribP3ui;
PFNGLVERTEXATTRIBP3UIVPROC _glVertexAttribP3uiv;
PFNGLVERTEXATTRIBP4UIPROC _glVertexAttribP4ui;
PFNGLVERTEXATTRIBP4UIVPROC _glVertexAttribP4uiv;

static void load_procs(void)
{
	_glCullFace = (PFNGLCULLFACEPROC) get_proc("glCullFace");
	_glFrontFace = (PFNGLFRONTFACEPROC) get_proc("glFrontFace");
	_glHint = (PFNGLHINTPROC) get_proc("glHint");
	_glLineWidth = (PFNGLLINEWIDTHPROC) get_proc("glLineWidth");
	_glPointSize = (PFNGLPOINTSIZEPROC) get_proc("glPointSize");
	_glPolygonMode = (PFNGLPOLYGONMODEPROC) get_proc("glPolygonMode");
	_glScissor = (PFNGLSCISSORPROC) get_proc("glScissor");
	_glTexParameterf = (PFNGLTEXPARAMETERFPROC) get_proc("glTexParameterf");
	_glTexParameterfv = (PFNGLTEXPARAMETERFVPROC) get_proc("glTexParameterfv");
	_glTexParameteri = (PFNGLTEXPARAMETERIPROC) get_proc("glTexParameteri");
	_glTexParameteriv = (PFNGLTEXPARAMETERIVPROC) get_proc("glTexParameteriv");
	_glTexImage1D = (PFNGLTEXIMAGE1DPROC) get_proc("glTexImage1D");
	_glTexImage2D = (PFNGLTEXIMAGE2DPROC) get_proc("glTexImage2D");
	_glDrawBuffer = (PFNGLDRAWBUFFERPROC) get_proc("glDrawBuffer");
	_glClear = (PFNGLCLEARPROC) get_proc("glClear");
	_glClearColor = (PFNGLCLEARCOLORPROC) get_proc("glClearColor");
	_glClearStencil = (PFNGLCLEARSTENCILPROC) get_proc("glClearStencil");
	_glClearDepth = (PFNGLCLEARDEPTHPROC) get_proc("glClearDepth");
	_glStencilMask = (PFNGLSTENCILMASKPROC) get_proc("glStencilMask");
	_glColorMask = (PFNGLCOLORMASKPROC) get_proc("glColorMask");
	_glDepthMask = (PFNGLDEPTHMASKPROC) get_proc("glDepthMask");
	_glDisable = (PFNGLDISABLEPROC) get_proc("glDisable");
	_glEnable = (PFNGLENABLEPROC) get_proc("glEnable");
	_glFinish = (PFNGLFINISHPROC) get_proc("glFinish");
	_glFlush = (PFNGLFLUSHPROC) get_proc("glFlush");
	_glBlendFunc = (PFNGLBLENDFUNCPROC) get_proc("glBlendFunc");
	_glLogicOp = (PFNGLLOGICOPPROC) get_proc("glLogicOp");
	_glStencilFunc = (PFNGLSTENCILFUNCPROC) get_proc("glStencilFunc");
	_glStencilOp = (PFNGLSTENCILOPPROC) get_proc("glStencilOp");
	_glDepthFunc = (PFNGLDEPTHFUNCPROC) get_proc("glDepthFunc");
	_glPixelStoref = (PFNGLPIXELSTOREFPROC) get_proc("glPixelStoref");
	_glPixelStorei = (PFNGLPIXELSTOREIPROC) get_proc("glPixelStorei");
	_glReadBuffer = (PFNGLREADBUFFERPROC) get_proc("glReadBuffer");
	_glReadPixels = (PFNGLREADPIXELSPROC) get_proc("glReadPixels");
	_glGetBooleanv = (PFNGLGETBOOLEANVPROC) get_proc("glGetBooleanv");
	_glGetDoublev = (PFNGLGETDOUBLEVPROC) get_proc("glGetDoublev");
	_glGetError = (PFNGLGETERRORPROC) get_proc("glGetError");
	_glGetFloatv = (PFNGLGETFLOATVPROC) get_proc("glGetFloatv");
	_glGetIntegerv = (PFNGLGETINTEGERVPROC) get_proc("glGetIntegerv");
	_glGetString = (PFNGLGETSTRINGPROC) get_proc("glGetString");
	_glGetTexImage = (PFNGLGETTEXIMAGEPROC) get_proc("glGetTexImage");
	_glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC) get_proc("glGetTexParameterfv");
	_glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC) get_proc("glGetTexParameteriv");
	_glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC) get_proc("glGetTexLevelParameterfv");
	_glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC) get_proc("glGetTexLevelParameteriv");
	_glIsEnabled = (PFNGLISENABLEDPROC) get_proc("glIsEnabled");
	_glDepthRange = (PFNGLDEPTHRANGEPROC) get_proc("glDepthRange");
	_glViewport = (PFNGLVIEWPORTPROC) get_proc("glViewport");
	_glDrawArrays = (PFNGLDRAWARRAYSPROC) get_proc("glDrawArrays");
	_glDrawElements = (PFNGLDRAWELEMENTSPROC) get_proc("glDrawElements");
	_glPolygonOffset = (PFNGLPOLYGONOFFSETPROC) get_proc("glPolygonOffset");
	_glCopyTexImage1D = (PFNGLCOPYTEXIMAGE1DPROC) get_proc("glCopyTexImage1D");
	_glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC) get_proc("glCopyTexImage2D");
	_glCopyTexSubImage1D = (PFNGLCOPYTEXSUBIMAGE1DPROC) get_proc("glCopyTexSubImage1D");
	_glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC) get_proc("glCopyTexSubImage2D");
	_glTexSubImage1D = (PFNGLTEXSUBIMAGE1DPROC) get_proc("glTexSubImage1D");
	_glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC) get_proc("glTexSubImage2D");
	_glBindTexture = (PFNGLBINDTEXTUREPROC) get_proc("glBindTexture");
	_glDeleteTextures = (PFNGLDELETETEXTURESPROC) get_proc("glDeleteTextures");
	_glGenTextures = (PFNGLGENTEXTURESPROC) get_proc("glGenTextures");
	_glIsTexture = (PFNGLISTEXTUREPROC) get_proc("glIsTexture");
	_glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC) get_proc("glDrawRangeElements");
	_glTexImage3D = (PFNGLTEXIMAGE3DPROC) get_proc("glTexImage3D");
	_glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC) get_proc("glTexSubImage3D");
	_glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC) get_proc("glCopyTexSubImage3D");
	_glActiveTexture = (PFNGLACTIVETEXTUREPROC) get_proc("glActiveTexture");
	_glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC) get_proc("glSampleCoverage");
	_glCompressedTexImage3D = (PFNGLCOMPRESSEDTEXIMAGE3DPROC) get_proc("glCompressedTexImage3D");
	_glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC) get_proc("glCompressedTexImage2D");
	_glCompressedTexImage1D = (PFNGLCOMPRESSEDTEXIMAGE1DPROC) get_proc("glCompressedTexImage1D");
	_glCompressedTexSubImage3D = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC) get_proc("glCompressedTexSubImage3D");
	_glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC) get_proc("glCompressedTexSubImage2D");
	_glCompressedTexSubImage1D = (PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC) get_proc("glCompressedTexSubImage1D");
	_glGetCompressedTexImage = (PFNGLGETCOMPRESSEDTEXIMAGEPROC) get_proc("glGetCompressedTexImage");
	_glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC) get_proc("glBlendFuncSeparate");
	_glMultiDrawArrays = (PFNGLMULTIDRAWARRAYSPROC) get_proc("glMultiDrawArrays");
	_glMultiDrawElements = (PFNGLMULTIDRAWELEMENTSPROC) get_proc("glMultiDrawElements");
	_glPointParameterf = (PFNGLPOINTPARAMETERFPROC) get_proc("glPointParameterf");
	_glPointParameterfv = (PFNGLPOINTPARAMETERFVPROC) get_proc("glPointParameterfv");
	_glPointParameteri = (PFNGLPOINTPARAMETERIPROC) get_proc("glPointParameteri");
	_glPointParameteriv = (PFNGLPOINTPARAMETERIVPROC) get_proc("glPointParameteriv");
	_glBlendColor = (PFNGLBLENDCOLORPROC) get_proc("glBlendColor");
	_glBlendEquation = (PFNGLBLENDEQUATIONPROC) get_proc("glBlendEquation");
	_glGenQueries = (PFNGLGENQUERIESPROC) get_proc("glGenQueries");
	_glDeleteQueries = (PFNGLDELETEQUERIESPROC) get_proc("glDeleteQueries");
	_glIsQuery = (PFNGLISQUERYPROC) get_proc("glIsQuery");
	_glBeginQuery = (PFNGLBEGINQUERYPROC) get_proc("glBeginQuery");
	_glEndQuery = (PFNGLENDQUERYPROC) get_proc("glEndQuery");
	_glGetQueryiv = (PFNGLGETQUERYIVPROC) get_proc("glGetQueryiv");
	_glGetQueryObjectiv = (PFNGLGETQUERYOBJECTIVPROC) get_proc("glGetQueryObjectiv");
	_glGetQueryObjectuiv = (PFNGLGETQUERYOBJECTUIVPROC) get_proc("glGetQueryObjectuiv");
	_glBindBuffer = (PFNGLBINDBUFFERPROC) get_proc("glBindBuffer");
	_glDeleteBuffers = (PFNGLDELETEBUFFERSPROC) get_proc("glDeleteBuffers");
	_glGenBuffers = (PFNGLGENBUFFERSPROC) get_proc("glGenBuffers");
	_glIsBuffer = (PFNGLISBUFFERPROC) get_proc("glIsBuffer");
	_glBufferData = (PFNGLBUFFERDATAPROC) get_proc("glBufferData");
	_glBufferSubData = (PFNGLBUFFERSUBDATAPROC) get_proc("glBufferSubData");
	_glGetBufferSubData = (PFNGLGETBUFFERSUBDATAPROC) get_proc("glGetBufferSubData");
	_glMapBuffer = (PFNGLMAPBUFFERPROC) get_proc("glMapBuffer");
	_glUnmapBuffer = (PFNGLUNMAPBUFFERPROC) get_proc("glUnmapBuffer");
	_glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC) get_proc("glGetBufferParameteriv");
	_glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC) get_proc("glGetBufferPointerv");
	_glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC) get_proc("glBlendEquationSeparate");
	_glDrawBuffers = (PFNGLDRAWBUFFERSPROC) get_proc("glDrawBuffers");
	_glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC) get_proc("glStencilOpSeparate");
	_glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC) get_proc("glStencilFuncSeparate");
	_glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC) get_proc("glStencilMaskSeparate");
	_glAttachShader = (PFNGLATTACHSHADERPROC) get_proc("glAttachShader");
	_glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC) get_proc("glBindAttribLocation");
	_glCompileShader = (PFNGLCOMPILESHADERPROC) get_proc("glCompileShader");
	_glCreateProgram = (PFNGLCREATEPROGRAMPROC) get_proc("glCreateProgram");
	_glCreateShader = (PFNGLCREATESHADERPROC) get_proc("glCreateShader");
	_glDeleteProgram = (PFNGLDELETEPROGRAMPROC) get_proc("glDeleteProgram");
	_glDeleteShader = (PFNGLDELETESHADERPROC) get_proc("glDeleteShader");
	_glDetachShader = (PFNGLDETACHSHADERPROC) get_proc("glDetachShader");
	_glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC) get_proc("glDisableVertexAttribArray");
	_glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC) get_proc("glEnableVertexAttribArray");
	_glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC) get_proc("glGetActiveAttrib");
	_glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC) get_proc("glGetActiveUniform");
	_glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC) get_proc("glGetAttachedShaders");
	_glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC) get_proc("glGetAttribLocation");
	_glGetProgramiv = (PFNGLGETPROGRAMIVPROC) get_proc("glGetProgramiv");
	_glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC) get_proc("glGetProgramInfoLog");
	_glGetShaderiv = (PFNGLGETSHADERIVPROC) get_proc("glGetShaderiv");
	_glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC) get_proc("glGetShaderInfoLog");
	_glGetShaderSource = (PFNGLGETSHADERSOURCEPROC) get_proc("glGetShaderSource");
	_glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC) get_proc("glGetUniformLocation");
	_glGetUniformfv = (PFNGLGETUNIFORMFVPROC) get_proc("glGetUniformfv");
	_glGetUniformiv = (PFNGLGETUNIFORMIVPROC) get_proc("glGetUniformiv");
	_glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC) get_proc("glGetVertexAttribdv");
	_glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC) get_proc("glGetVertexAttribfv");
	_glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC) get_proc("glGetVertexAttribiv");
	_glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC) get_proc("glGetVertexAttribPointerv");
	_glIsProgram = (PFNGLISPROGRAMPROC) get_proc("glIsProgram");
	_glIsShader = (PFNGLISSHADERPROC) get_proc("glIsShader");
	_glLinkProgram = (PFNGLLINKPROGRAMPROC) get_proc("glLinkProgram");
	_glShaderSource = (PFNGLSHADERSOURCEPROC) get_proc("glShaderSource");
	_glUseProgram = (PFNGLUSEPROGRAMPROC) get_proc("glUseProgram");
	_glUniform1f = (PFNGLUNIFORM1FPROC) get_proc("glUniform1f");
	_glUniform2f = (PFNGLUNIFORM2FPROC) get_proc("glUniform2f");
	_glUniform3f = (PFNGLUNIFORM3FPROC) get_proc("glUniform3f");
	_glUniform4f = (PFNGLUNIFORM4FPROC) get_proc("glUniform4f");
	_glUniform1i = (PFNGLUNIFORM1IPROC) get_proc("glUniform1i");
	_glUniform2i = (PFNGLUNIFORM2IPROC) get_proc("glUniform2i");
	_glUniform3i = (PFNGLUNIFORM3IPROC) get_proc("glUniform3i");
	_glUniform4i = (PFNGLUNIFORM4IPROC) get_proc("glUniform4i");
	_glUniform1fv = (PFNGLUNIFORM1FVPROC) get_proc("glUniform1fv");
	_glUniform2fv = (PFNGLUNIFORM2FVPROC) get_proc("glUniform2fv");
	_glUniform3fv = (PFNGLUNIFORM3FVPROC) get_proc("glUniform3fv");
	_glUniform4fv = (PFNGLUNIFORM4FVPROC) get_proc("glUniform4fv");
	_glUniform1iv = (PFNGLUNIFORM1IVPROC) get_proc("glUniform1iv");
	_glUniform2iv = (PFNGLUNIFORM2IVPROC) get_proc("glUniform2iv");
	_glUniform3iv = (PFNGLUNIFORM3IVPROC) get_proc("glUniform3iv");
	_glUniform4iv = (PFNGLUNIFORM4IVPROC) get_proc("glUniform4iv");
	_glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC) get_proc("glUniformMatrix2fv");
	_glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC) get_proc("glUniformMatrix3fv");
	_glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC) get_proc("glUniformMatrix4fv");
	_glValidateProgram = (PFNGLVALIDATEPROGRAMPROC) get_proc("glValidateProgram");
	_glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC) get_proc("glVertexAttrib1d");
	_glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC) get_proc("glVertexAttrib1dv");
	_glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC) get_proc("glVertexAttrib1f");
	_glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC) get_proc("glVertexAttrib1fv");
	_glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC) get_proc("glVertexAttrib1s");
	_glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC) get_proc("glVertexAttrib1sv");
	_glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC) get_proc("glVertexAttrib2d");
	_glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC) get_proc("glVertexAttrib2dv");
	_glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC) get_proc("glVertexAttrib2f");
	_glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC) get_proc("glVertexAttrib2fv");
	_glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC) get_proc("glVertexAttrib2s");
	_glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC) get_proc("glVertexAttrib2sv");
	_glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC) get_proc("glVertexAttrib3d");
	_glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC) get_proc("glVertexAttrib3dv");
	_glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC) get_proc("glVertexAttrib3f");
	_glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC) get_proc("glVertexAttrib3fv");
	_glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC) get_proc("glVertexAttrib3s");
	_glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC) get_proc("glVertexAttrib3sv");
	_glVertexAttrib4Nbv = (PFNGLVERTEXATTRIB4NBVPROC) get_proc("glVertexAttrib4Nbv");
	_glVertexAttrib4Niv = (PFNGLVERTEXATTRIB4NIVPROC) get_proc("glVertexAttrib4Niv");
	_glVertexAttrib4Nsv = (PFNGLVERTEXATTRIB4NSVPROC) get_proc("glVertexAttrib4Nsv");
	_glVertexAttrib4Nub = (PFNGLVERTEXATTRIB4NUBPROC) get_proc("glVertexAttrib4Nub");
	_glVertexAttrib4Nubv = (PFNGLVERTEXATTRIB4NUBVPROC) get_proc("glVertexAttrib4Nubv");
	_glVertexAttrib4Nuiv = (PFNGLVERTEXATTRIB4NUIVPROC) get_proc("glVertexAttrib4Nuiv");
	_glVertexAttrib4Nusv = (PFNGLVERTEXATTRIB4NUSVPROC) get_proc("glVertexAttrib4Nusv");
	_glVertexAttrib4bv = (PFNGLVERTEXATTRIB4BVPROC) get_proc("glVertexAttrib4bv");
	_glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC) get_proc("glVertexAttrib4d");
	_glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC) get_proc("glVertexAttrib4dv");
	_glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC) get_proc("glVertexAttrib4f");
	_glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC) get_proc("glVertexAttrib4fv");
	_glVertexAttrib4iv = (PFNGLVERTEXATTRIB4IVPROC) get_proc("glVertexAttrib4iv");
	_glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC) get_proc("glVertexAttrib4s");
	_glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC) get_proc("glVertexAttrib4sv");
	_glVertexAttrib4ubv = (PFNGLVERTEXATTRIB4UBVPROC) get_proc("glVertexAttrib4ubv");
	_glVertexAttrib4uiv = (PFNGLVERTEXATTRIB4UIVPROC) get_proc("glVertexAttrib4uiv");
	_glVertexAttrib4usv = (PFNGLVERTEXATTRIB4USVPROC) get_proc("glVertexAttrib4usv");
	_glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC) get_proc("glVertexAttribPointer");
	_glUniformMatrix2x3fv = (PFNGLUNIFORMMATRIX2X3FVPROC) get_proc("glUniformMatrix2x3fv");
	_glUniformMatrix3x2fv = (PFNGLUNIFORMMATRIX3X2FVPROC) get_proc("glUniformMatrix3x2fv");
	_glUniformMatrix2x4fv = (PFNGLUNIFORMMATRIX2X4FVPROC) get_proc("glUniformMatrix2x4fv");
	_glUniformMatrix4x2fv = (PFNGLUNIFORMMATRIX4X2FVPROC) get_proc("glUniformMatrix4x2fv");
	_glUniformMatrix3x4fv = (PFNGLUNIFORMMATRIX3X4FVPROC) get_proc("glUniformMatrix3x4fv");
	_glUniformMatrix4x3fv = (PFNGLUNIFORMMATRIX4X3FVPROC) get_proc("glUniformMatrix4x3fv");
	_glColorMaski = (PFNGLCOLORMASKIPROC) get_proc("glColorMaski");
	_glGetBooleani_v = (PFNGLGETBOOLEANI_VPROC) get_proc("glGetBooleani_v");
	_glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC) get_proc("glGetIntegeri_v");
	_glEnablei = (PFNGLENABLEIPROC) get_proc("glEnablei");
	_glDisablei = (PFNGLDISABLEIPROC) get_proc("glDisablei");
	_glIsEnabledi = (PFNGLISENABLEDIPROC) get_proc("glIsEnabledi");
	_glBeginTransformFeedback = (PFNGLBEGINTRANSFORMFEEDBACKPROC) get_proc("glBeginTransformFeedback");
	_glEndTransformFeedback = (PFNGLENDTRANSFORMFEEDBACKPROC) get_proc("glEndTransformFeedback");
	_glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC) get_proc("glBindBufferRange");
	_glBindBufferBase = (PFNGLBINDBUFFERBASEPROC) get_proc("glBindBufferBase");
	_glTransformFeedbackVaryings = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC) get_proc("glTransformFeedbackVaryings");
	_glGetTransformFeedbackVarying = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC) get_proc("glGetTransformFeedbackVarying");
	_glClampColor = (PFNGLCLAMPCOLORPROC) get_proc("glClampColor");
	_glBeginConditionalRender = (PFNGLBEGINCONDITIONALRENDERPROC) get_proc("glBeginConditionalRender");
	_glEndConditionalRender = (PFNGLENDCONDITIONALRENDERPROC) get_proc("glEndConditionalRender");
	_glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC) get_proc("glVertexAttribIPointer");
	_glGetVertexAttribIiv = (PFNGLGETVERTEXATTRIBIIVPROC) get_proc("glGetVertexAttribIiv");
	_glGetVertexAttribIuiv = (PFNGLGETVERTEXATTRIBIUIVPROC) get_proc("glGetVertexAttribIuiv");
	_glVertexAttribI1i = (PFNGLVERTEXATTRIBI1IPROC) get_proc("glVertexAttribI1i");
	_glVertexAttribI2i = (PFNGLVERTEXATTRIBI2IPROC) get_proc("glVertexAttribI2i");
	_glVertexAttribI3i = (PFNGLVERTEXATTRIBI3IPROC) get_proc("glVertexAttribI3i");
	_glVertexAttribI4i = (PFNGLVERTEXATTRIBI4IPROC) get_proc("glVertexAttribI4i");
	_glVertexAttribI1ui = (PFNGLVERTEXATTRIBI1UIPROC) get_proc("glVertexAttribI1ui");
	_glVertexAttribI2ui = (PFNGLVERTEXATTRIBI2UIPROC) get_proc("glVertexAttribI2ui");
	_glVertexAttribI3ui = (PFNGLVERTEXATTRIBI3UIPROC) get_proc("glVertexAttribI3ui");
	_glVertexAttribI4ui = (PFNGLVERTEXATTRIBI4UIPROC) get_proc("glVertexAttribI4ui");
	_glVertexAttribI1iv = (PFNGLVERTEXATTRIBI1IVPROC) get_proc("glVertexAttribI1iv");
	_glVertexAttribI2iv = (PFNGLVERTEXATTRIBI2IVPROC) get_proc("glVertexAttribI2iv");
	_glVertexAttribI3iv = (PFNGLVERTEXATTRIBI3IVPROC) get_proc("glVertexAttribI3iv");
	_glVertexAttribI4iv = (PFNGLVERTEXATTRIBI4IVPROC) get_proc("glVertexAttribI4iv");
	_glVertexAttribI1uiv = (PFNGLVERTEXATTRIBI1UIVPROC) get_proc("glVertexAttribI1uiv");
	_glVertexAttribI2uiv = (PFNGLVERTEXATTRIBI2UIVPROC) get_proc("glVertexAttribI2uiv");
	_glVertexAttribI3uiv = (PFNGLVERTEXATTRIBI3UIVPROC) get_proc("glVertexAttribI3uiv");
	_glVertexAttribI4uiv = (PFNGLVERTEXATTRIBI4UIVPROC) get_proc("glVertexAttribI4uiv");
	_glVertexAttribI4bv = (PFNGLVERTEXATTRIBI4BVPROC) get_proc("glVertexAttribI4bv");
	_glVertexAttribI4sv = (PFNGLVERTEXATTRIBI4SVPROC) get_proc("glVertexAttribI4sv");
	_glVertexAttribI4ubv = (PFNGLVERTEXATTRIBI4UBVPROC) get_proc("glVertexAttribI4ubv");
	_glVertexAttribI4usv = (PFNGLVERTEXATTRIBI4USVPROC) get_proc("glVertexAttribI4usv");
	_glGetUniformuiv = (PFNGLGETUNIFORMUIVPROC) get_proc("glGetUniformuiv");
	_glBindFragDataLocation = (PFNGLBINDFRAGDATALOCATIONPROC) get_proc("glBindFragDataLocation");
	_glGetFragDataLocation = (PFNGLGETFRAGDATALOCATIONPROC) get_proc("glGetFragDataLocation");
	_glUniform1ui = (PFNGLUNIFORM1UIPROC) get_proc("glUniform1ui");
	_glUniform2ui = (PFNGLUNIFORM2UIPROC) get_proc("glUniform2ui");
	_glUniform3ui = (PFNGLUNIFORM3UIPROC) get_proc("glUniform3ui");
	_glUniform4ui = (PFNGLUNIFORM4UIPROC) get_proc("glUniform4ui");
	_glUniform1uiv = (PFNGLUNIFORM1UIVPROC) get_proc("glUniform1uiv");
	_glUniform2uiv = (PFNGLUNIFORM2UIVPROC) get_proc("glUniform2uiv");
	_glUniform3uiv = (PFNGLUNIFORM3UIVPROC) get_proc("glUniform3uiv");
	_glUniform4uiv = (PFNGLUNIFORM4UIVPROC) get_proc("glUniform4uiv");
	_glTexParameterIiv = (PFNGLTEXPARAMETERIIVPROC) get_proc("glTexParameterIiv");
	_glTexParameterIuiv = (PFNGLTEXPARAMETERIUIVPROC) get_proc("glTexParameterIuiv");
	_glGetTexParameterIiv = (PFNGLGETTEXPARAMETERIIVPROC) get_proc("glGetTexParameterIiv");
	_glGetTexParameterIuiv = (PFNGLGETTEXPARAMETERIUIVPROC) get_proc("glGetTexParameterIuiv");
	_glClearBufferiv = (PFNGLCLEARBUFFERIVPROC) get_proc("glClearBufferiv");
	_glClearBufferuiv = (PFNGLCLEARBUFFERUIVPROC) get_proc("glClearBufferuiv");
	_glClearBufferfv = (PFNGLCLEARBUFFERFVPROC) get_proc("glClearBufferfv");
	_glClearBufferfi = (PFNGLCLEARBUFFERFIPROC) get_proc("glClearBufferfi");
	_glGetStringi = (PFNGLGETSTRINGIPROC) get_proc("glGetStringi");
	_glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC) get_proc("glIsRenderbuffer");
	_glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC) get_proc("glBindRenderbuffer");
	_glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC) get_proc("glDeleteRenderbuffers");
	_glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC) get_proc("glGenRenderbuffers");
	_glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC) get_proc("glRenderbufferStorage");
	_glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC) get_proc("glGetRenderbufferParameteriv");
	_glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC) get_proc("glIsFramebuffer");
	_glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC) get_proc("glBindFramebuffer");
	_glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC) get_proc("glDeleteFramebuffers");
	_glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC) get_proc("glGenFramebuffers");
	_glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC) get_proc("glCheckFramebufferStatus");
	_glFramebufferTexture1D = (PFNGLFRAMEBUFFERTEXTURE1DPROC) get_proc("glFramebufferTexture1D");
	_glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC) get_proc("glFramebufferTexture2D");
	_glFramebufferTexture3D = (PFNGLFRAMEBUFFERTEXTURE3DPROC) get_proc("glFramebufferTexture3D");
	_glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC) get_proc("glFramebufferRenderbuffer");
	_glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC) get_proc("glGetFramebufferAttachmentParameteriv");
	_glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC) get_proc("glGenerateMipmap");
	_glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC) get_proc("glBlitFramebuffer");
	_glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC) get_proc("glRenderbufferStorageMultisample");
	_glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC) get_proc("glFramebufferTextureLayer");
	_glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC) get_proc("glMapBufferRange");
	_glFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC) get_proc("glFlushMappedBufferRange");
	_glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC) get_proc("glBindVertexArray");
	_glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC) get_proc("glDeleteVertexArrays");
	_glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC) get_proc("glGenVertexArrays");
	_glIsVertexArray = (PFNGLISVERTEXARRAYPROC) get_proc("glIsVertexArray");
	_glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC) get_proc("glDrawArraysInstanced");
	_glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC) get_proc("glDrawElementsInstanced");
	_glTexBuffer = (PFNGLTEXBUFFERPROC) get_proc("glTexBuffer");
	_glPrimitiveRestartIndex = (PFNGLPRIMITIVERESTARTINDEXPROC) get_proc("glPrimitiveRestartIndex");
	_glCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC) get_proc("glCopyBufferSubData");
	_glGetUniformIndices = (PFNGLGETUNIFORMINDICESPROC) get_proc("glGetUniformIndices");
	_glGetActiveUniformsiv = (PFNGLGETACTIVEUNIFORMSIVPROC) get_proc("glGetActiveUniformsiv");
	_glGetActiveUniformName = (PFNGLGETACTIVEUNIFORMNAMEPROC) get_proc("glGetActiveUniformName");
	_glGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC) get_proc("glGetUniformBlockIndex");
	_glGetActiveUniformBlockiv = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC) get_proc("glGetActiveUniformBlockiv");
	_glGetActiveUniformBlockName = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC) get_proc("glGetActiveUniformBlockName");
	_glUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC) get_proc("glUniformBlockBinding");
	_glDrawElementsBaseVertex = (PFNGLDRAWELEMENTSBASEVERTEXPROC) get_proc("glDrawElementsBaseVertex");
	_glDrawRangeElementsBaseVertex = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC) get_proc("glDrawRangeElementsBaseVertex");
	_glDrawElementsInstancedBaseVertex = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC) get_proc("glDrawElementsInstancedBaseVertex");
	_glMultiDrawElementsBaseVertex = (PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC) get_proc("glMultiDrawElementsBaseVertex");
	_glProvokingVertex = (PFNGLPROVOKINGVERTEXPROC) get_proc("glProvokingVertex");
	_glFenceSync = (PFNGLFENCESYNCPROC) get_proc("glFenceSync");
	_glIsSync = (PFNGLISSYNCPROC) get_proc("glIsSync");
	_glDeleteSync = (PFNGLDELETESYNCPROC) get_proc("glDeleteSync");
	_glClientWaitSync = (PFNGLCLIENTWAITSYNCPROC) get_proc("glClientWaitSync");
	_glWaitSync = (PFNGLWAITSYNCPROC) get_proc("glWaitSync");
	_glGetInteger64v = (PFNGLGETINTEGER64VPROC) get_proc("glGetInteger64v");
	_glGetSynciv = (PFNGLGETSYNCIVPROC) get_proc("glGetSynciv");
	_glGetInteger64i_v = (PFNGLGETINTEGER64I_VPROC) get_proc("glGetInteger64i_v");
	_glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC) get_proc("glGetBufferParameteri64v");
	_glFramebufferTexture = (PFNGLFRAMEBUFFERTEXTUREPROC) get_proc("glFramebufferTexture");
	_glTexImage2DMultisample = (PFNGLTEXIMAGE2DMULTISAMPLEPROC) get_proc("glTexImage2DMultisample");
	_glTexImage3DMultisample = (PFNGLTEXIMAGE3DMULTISAMPLEPROC) get_proc("glTexImage3DMultisample");
	_glGetMultisamplefv = (PFNGLGETMULTISAMPLEFVPROC) get_proc("glGetMultisamplefv");
	_glSampleMaski = (PFNGLSAMPLEMASKIPROC) get_proc("glSampleMaski");
	_glBindFragDataLocationIndexed = (PFNGLBINDFRAGDATALOCATIONINDEXEDPROC) get_proc("glBindFragDataLocationIndexed");
	_glGetFragDataIndex = (PFNGLGETFRAGDATAINDEXPROC) get_proc("glGetFragDataIndex");
	_glGenSamplers = (PFNGLGENSAMPLERSPROC) get_proc("glGenSamplers");
	_glDeleteSamplers = (PFNGLDELETESAMPLERSPROC) get_proc("glDeleteSamplers");
	_glIsSampler = (PFNGLISSAMPLERPROC) get_proc("glIsSampler");
	_glBindSampler = (PFNGLBINDSAMPLERPROC) get_proc("glBindSampler");
	_glSamplerParameteri = (PFNGLSAMPLERPARAMETERIPROC) get_proc("glSamplerParameteri");
	_glSamplerParameteriv = (PFNGLSAMPLERPARAMETERIVPROC) get_proc("glSamplerParameteriv");
	_glSamplerParameterf = (PFNGLSAMPLERPARAMETERFPROC) get_proc("glSamplerParameterf");
	_glSamplerParameterfv = (PFNGLSAMPLERPARAMETERFVPROC) get_proc("glSamplerParameterfv");
	_glSamplerParameterIiv = (PFNGLSAMPLERPARAMETERIIVPROC) get_proc("glSamplerParameterIiv");
	_glSamplerParameterIuiv = (PFNGLSAMPLERPARAMETERIUIVPROC) get_proc("glSamplerParameterIuiv");
	_glGetSamplerParameteriv = (PFNGLGETSAMPLERPARAMETERIVPROC) get_proc("glGetSamplerParameteriv");
	_glGetSamplerParameterIiv = (PFNGLGETSAMPLERPARAMETERIIVPROC) get_proc("glGetSamplerParameterIiv");
	_glGetSamplerParameterfv = (PFNGLGETSAMPLERPARAMETERFVPROC) get_proc("glGetSamplerParameterfv");
	_glGetSamplerParameterIuiv = (PFNGLGETSAMPLERPARAMETERIUIVPROC) get_proc("glGetSamplerParameterIuiv");
	_glQueryCounter = (PFNGLQUERYCOUNTERPROC) get_proc("glQueryCounter");
	_glGetQueryObjecti64v = (PFNGLGETQUERYOBJECTI64VPROC) get_proc("glGetQueryObjecti64v");
	_glGetQueryObjectui64v = (PFNGLGETQUERYOBJECTUI64VPROC) get_proc("glGetQueryObjectui64v");
	_glVertexAttribDivisor = (PFNGLVERTEXATTRIBDIVISORPROC) get_proc("glVertexAttribDivisor");
	_glVertexAttribP1ui = (PFNGLVERTEXATTRIBP1UIPROC) get_proc("glVertexAttribP1ui");
	_glVertexAttribP1uiv = (PFNGLVERTEXATTRIBP1UIVPROC) get_proc("glVertexAttribP1uiv");
	_glVertexAttribP2ui = (PFNGLVERTEXATTRIBP2UIPROC) get_proc("glVertexAttribP2ui");
	_glVertexAttribP2uiv = (PFNGLVERTEXATTRIBP2UIVPROC) get_proc("glVertexAttribP2uiv");
	_glVertexAttribP3ui = (PFNGLVERTEXATTRIBP3UIPROC) get_proc("glVertexAttribP3ui");
	_glVertexAttribP3uiv = (PFNGLVERTEXATTRIBP3UIVPROC) get_proc("glVertexAttribP3uiv");
	_glVertexAttribP4ui = (PFNGLVERTEXATTRIBP4UIPROC) get_proc("glVertexAttribP4ui");
	_glVertexAttribP4uiv = (PFNGLVERTEXATTRIBP4UIVPROC) get_proc("glVertexAttribP4uiv");
}

static void load_exts(void)
{
}
